language: csharp
solution: OpenDutchLemmatizer.sln
install:
  - nuget restore OpenDutchLemmatizer.sln
  - nuget install NUnit.Runners -Version 3.10.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release OpenDutchLemmatizer.sln
  - mono ./testrunner/NUnit.Runners.*/tools/nunit-console.exe ./OpenDutchLemmatizerTest/bin/Release/OpenDutchLemmatizerTest.dll
